language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"

sudo: false

script:
  - make test-cov

after_script:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null 2>&1
